version: "3.9"
services:
  psql:
    image: postgres:15.3
    container_name: projtest_psql
    restart: always
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env-dev
  django:
    container_name: projtest_django
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    env_file:
      - .env-dev
    command: pipenv run python manage.py runserver 0:8000
    volumes:
      - ..:/opt/:delegated
    ports:
      - 8000:8000
    depends_on:
      - psql
  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379:6379
  worker:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    env_file:
      - .env-dev
    command: pipenv run celery -A main worker -l DEBUG
    volumes:
      - ..:/opt/:delegated
    depends_on:
      - psql
      - redis
  beat:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    env_file:
      - .env-dev
    command: pipenv run celery -A main beat -l DEBUG
    volumes:
      - ..:/opt/:delegated
    depends_on:
      - psql
      - redis