# Generated by Django 4.2.5 on 2023-09-18 22:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py'])], verbose_name='Файл для проверки')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('new', 'new'), ('processing', 'processing'), ('ok', 'ok'), ('failed', 'failed'), ('done', 'done')], default='new', max_length=20, verbose_name='Статус')),
                ('result', models.TextField(blank=True, verbose_name='Отчёт проверки')),
                ('is_sent_to_email', models.BooleanField(verbose_name='Отправлено на почту')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='fileman.file', verbose_name='Логи')),
            ],
        ),
    ]
