# Generated by Django 4.2.5 on 2023-09-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='is_sent_to_email',
            field=models.BooleanField(default=False, verbose_name='Sent to mail'),
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('processing', 'processing'), ('done', 'done')], default='new', max_length=20, verbose_name='Statuses'),
        ),
    ]
